// Code generated by "stringer -type=ObjectType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OBJ_INVALID-0]
	_ = x[OBJ_COMMIT-1]
	_ = x[OBJ_TREE-2]
	_ = x[OBJ_BLOB-3]
	_ = x[OBJ_TAG-4]
	_ = x[OBJ_OFS_DELTA-6]
	_ = x[OBJ_REF_DELTA-7]
}

const (
	_ObjectType_name_0 = "OBJ_INVALIDOBJ_COMMITOBJ_TREEOBJ_BLOBOBJ_TAG"
	_ObjectType_name_1 = "OBJ_OFS_DELTAOBJ_REF_DELTA"
)

var (
	_ObjectType_index_0 = [...]uint8{0, 11, 21, 29, 37, 44}
	_ObjectType_index_1 = [...]uint8{0, 13, 26}
)

func (i ObjectType) String() string {
	switch {
	case i <= 4:
		return _ObjectType_name_0[_ObjectType_index_0[i]:_ObjectType_index_0[i+1]]
	case 6 <= i && i <= 7:
		i -= 6
		return _ObjectType_name_1[_ObjectType_index_1[i]:_ObjectType_index_1[i+1]]
	default:
		return "ObjectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
